//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int idAdmin { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Pais { get; set; }
        public string ZonaHoraria { get; set; }
        public string idAdministrador { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
