//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaMaestro
    {
        public int idClase { get; set; }
        public int idMaestro { get; set; }
        public int idAlumno { get; set; }
        public System.DateTime FechaCita { get; set; }
        public string StatusCita { get; set; }
        public string ZonaHoraria { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Maestro Maestro { get; set; }
    }
}
