//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.AgendaMaestro = new HashSet<AgendaMaestro>();
            this.HistorialCompraHoras = new HashSet<HistorialCompraHoras>();
            this.HistorialReporteHoras = new HashSet<HistorialReporteHoras>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> HorasCompradas { get; set; }
        public string ZonaHoraria { get; set; }
        public string idAlumno { get; set; }
        public Nullable<int> idMaestroAsignado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendaMaestro> AgendaMaestro { get; set; }
        public virtual Maestro Maestro { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialCompraHoras> HistorialCompraHoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialReporteHoras> HistorialReporteHoras { get; set; }
    }
}
