//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningPlatform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELearningEntities : DbContext
    {
        public ELearningEntities()
            : base("name=ELearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<AgendaMaestro> AgendaMaestro { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Configuraciones> Configuraciones { get; set; }
        public virtual DbSet<HistorialCompraHoras> HistorialCompraHoras { get; set; }
        public virtual DbSet<HistorialReporteHoras> HistorialReporteHoras { get; set; }
        public virtual DbSet<Maestro> Maestro { get; set; }
        public virtual DbSet<ReglasPrecios> ReglasPrecios { get; set; }
        public virtual DbSet<SolicitudRegistroMaestro> SolicitudRegistroMaestro { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
