//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCompraHoras
    {
        public int idCompra { get; set; }
        public int NumeroHoras { get; set; }
        public int idAlumno { get; set; }
        public System.DateTime FechaCommpra { get; set; }
        public int Importe { get; set; }
        public string ZonaHoraria { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
