//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearningPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglasPrecios
    {
        public int idRegla { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CantidadInicialHoras { get; set; }
        public int CantidadFinalHoras { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> PrecioHora { get; set; }
    }
}
